name: Node.js Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t fredgad/hub-image .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag fredgad/hub-image fredgad/hub-image
          docker push fredgad/hub-image

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy Docker container
        run: |
          docker run -d -p 3000:3000 -p 9000:9000 fredgad/hub-image
